### ISSUE TITLE
code pane swapping tabs not working in Chrome

### ISSUE THREAD

**Issue by markhillard** [markhillard/Editor#6]
Possible fix:

``` css
.code-pane-* {
position:absolute;
visibility:hidden;
}
```
